<?php //if($_imageUrl=$this->getCurrentCategory()->getImageUrl()): ?>
    <div class="category-view">
        <div class="category-image"><img src="https://panneer-24-us.codemapp.com/media/catalog/category/banner-01.jpg" alt="Collections" title="Collections" class="image"></div>
            <div class="category-description">
                <style>#html-body [data-pb-style=OINA3PM]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}</style>
                <div data-content-type="row" data-appearance="contained" data-element="main">
                    <div data-enable-parallax="0" data-parallax-speed="0.5" data-background-images="{}" data-background-type="image" data-video-loop="true" data-video-play-only-visible="true" data-video-lazy-load="true" data-video-fallback-src="" data-element="inner" data-pb-style="OINA3PM">
                        <div data-content-type="text" data-appearance="default" data-element="main">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus consectetur voluptas minima, tenetur ullam quisquam recusandae quibusdam, distinctio. Amet ipsa, dignissimos, consequuntur tenetur nesciunt qui eum voluptas cupiditate aperiam minima sunt dolores vel impedit fugiat quos minus maiores, ut laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus consectetur voluptas minima, tenetur ullam quisquam recusandae quibusdam, distinctio. Amet ipsa, dignissimos, consequuntur tenetur nesciunt qui eum voluptas cupiditate aperiam minima sunt dolores vel impedit fugiat quos minus maiores, ut laborum.</p>
                        </div>
                        <button class="readmore action subscribe primary" type="button" >Read More</button>
                    </div>
                </div>
            </div>
        </div>
<?php //endif; ?>